name: CI Tests
on: [push]
jobs:
  run-tests:
    name: PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_PASSWORD: 'password'
          MYSQL_DATABASE: test
          MYSQL_ROOT_HOST: '%'
          MYSQL_USER: 'fred'
          MYSQL_PASSWORD: 'bloggs'
        ports:
          - 13306:13306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.3', '7.4']
    steps:
      - uses: actions/checkout@v1
      - name: Check MySQL Version
        run: mysqladmin version --user=fred --password=bloggs --host=127.0.0.1 --port=13306
      - name: Setup PHP Action
        uses: shivammathur/setup-php@1.6.1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: pdo_mysql,mbstring
          coverage: pcov
      - name: Validate composer.json and composer.lock
        run: composer validate
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: CS-Check
        run: composer cs-check
      - name: Test
        run: composer test-coverage
